#version 460
layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0, rgba32f) readonly uniform image2D depthDominant;
layout(binding = 1, rg32f) writeonly uniform image2D gridMinMax; // .x = min, .y = max

void main() {
    ivec2 gridCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 gridSize = imageSize(gridMinMax);
    ivec2 cellSize = imageSize(depthDominant) / gridSize;

    float minDepth = 1e20;
    float maxDepth = -1e20;
    for (int y = 0; y < cellSize.y; ++y)
    for (int x = 0; x < cellSize.x; ++x) {
        ivec2 pix = gridCoord * cellSize + ivec2(x, y);
        float d = imageLoad(depthDominant, pix).x;
        minDepth = min(minDepth, d);
        maxDepth = max(maxDepth, d);
    }
    imageStore(gridMinMax, gridCoord, vec4(minDepth, maxDepth, 0, 0));
}