/*
 * Copyright (c) 2019-2021, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: Copyright (c) 2019-2021 NVIDIA CORPORATION
 * SPDX-License-Identifier: Apache-2.0
 */
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_shader_image_load_formatted : enable  // The folowing extension allow to pass images as function parameters

#include "device_host.h"
#include "dh_bindings.h"
#include "payload.glsl"
#include "nvvkhl/shaders/random.h"
#include "nvvkhl/shaders/constants.h"
#include "compress.glsl"

// clang-format off
layout(location = 0) rayPayloadEXT HitPayload payload;
layout(location = 1) rayPayloadEXT GbufferPayload payloadGbuf;

layout(set = 0, binding = eTlas) uniform accelerationStructureEXT topLevelAS;
// #OPTIX_D
layout(set = 0, binding = eOutImage) uniform image2D image;
layout(set = 0, binding = eOutAlbedo) uniform image2D gAlbedo;
layout(set = 0, binding = eOutNormal) uniform image2D gNormal;

layout(set = 1, binding = eFrameInfo) uniform FrameInfo_ { FrameInfo frameInfo[2]; };
// clang-format on

layout(push_constant) uniform RtxPushConstant_
{
  PushConstant pc;
};

// #OPTIX_D
vec4 gUnpackedAlbedo = vec4(0);
vec3 gUnpackedNormal = vec3(0);
float dist = 0.0;
float radius = 0.0;
bool skipPixel = false;
bool intertwine = false; // To drawn outer pixels n the border zone
bool skippingArea = false;  
bool isLeftView = false;

//-----------------------------------------------------------------------
// Sampling the pixel
//-----------------------------------------------------------------------
vec3 samplePixel(inout uint seed, vec2 adjustedPixelPos)
{
  // Subpixel jitter: send the ray through a different position inside the pixel each time, to provide antialiasing.
  vec2 subpixel_jitter = pc.frame == 0 ? vec2(0.5f, 0.5f) : vec2(rand(seed), rand(seed));

  const vec2 pixelCenter = adjustedPixelPos + subpixel_jitter;
  const vec2 inUV        = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
  const vec2 d           = inUV * 2.0 - 1.0;


  mat4 viewInv, projInv;

    // Check if the pixel is outside the circular pattern
  if (isLeftView && dist > radius)
  {
    // If left view and the pixel is outside the circular pattern
    if (!skippingArea) 
    {
      viewInv = inverse(frameInfo[0].view2);
      projInv = inverse(frameInfo[0].proj2);
    }
    else { // If the pixel is an area around the circular pattern
      // 50% of pixels are drawn from each view
      if(intertwine){      
        viewInv = inverse(frameInfo[0].view2);
        projInv = inverse(frameInfo[0].proj2);
      }
      else{
        viewInv = inverse(frameInfo[0].view);
        projInv = inverse(frameInfo[0].proj);
      }
    }
  }
  else if (!isLeftView)
  {
    viewInv = inverse(frameInfo[0].view2);
    projInv = inverse(frameInfo[0].proj2);
  }
  else
  {
    viewInv = inverse(frameInfo[0].view);
    projInv = inverse(frameInfo[0].proj);
  }

  vec4 origin    = viewInv * vec4(0.0, 0.0, 0.0, 1.0);
  vec4 target    = projInv * vec4(d.x, d.y, 0.01, 1.0);
  vec4 direction = viewInv * vec4(normalize(target.xyz), 0.0);

  const uint  rayFlags  = gl_RayFlagsCullBackFacingTrianglesEXT;
  const float tMin      = 0.001;
  const float tMax      = INFINITE;

  payload.contrib      = vec3(0.0, 0.0, 0.0);
  payload.weight       = vec3(1.0, 1.0, 1.0);
  payload.seed         = seed;
  payload.hitT         = INFINITE;
  payload.rayOrigin    = origin.xyz;
  payload.rayDirection = direction.xyz;

  vec3 weightAccum  = vec3(1.0, 1.0, 1.0);
  vec3 contribAccum = vec3(0.0, 0.0, 0.0);

  for(int depth = 0; depth < pc.maxDepth; depth++)
  {
    traceRayEXT(topLevelAS,            // acceleration structure
                rayFlags,              // rayFlags
                0xFF,                  // cullMask
                0,                     // sbtRecordOffset
                0,                     // sbtRecordStride
                0,                     // missIndex
                payload.rayOrigin,     // ray origin
                tMin,                  // ray min range
                payload.rayDirection,  // ray direction
                tMax,                  // ray max range
                0                      // payload (location = 0)
    );
    // Accumulating results
    contribAccum += payload.contrib * weightAccum;
    weightAccum *= payload.weight;

    // Stopping recursion
    if(payload.hitT == INFINITE)
      break;

    // Russian-Roulette
    float rrPcont = min(max(weightAccum.x, max(weightAccum.y, weightAccum.z)) + 0.001, 0.95);
    if(rand(payload.seed) >= rrPcont)
      break;  // paths with low throughput that won't contribute
    weightAccum /= rrPcont;
  }

  // Removing fireflies
  float lum = dot(contribAccum, vec3(0.212671f, 0.715160f, 0.072169f));
  if(lum > frameInfo[0].maxLuminance)
  {
    contribAccum *= frameInfo[0].maxLuminance / lum;
  }

  seed = payload.seed;
  return contribAccum;
}


//-----------------------------------------------------------------------
// Trace a single ray in the middle of the pixel to retrieve the
// Albedo and normal. Also, forcing all objects to be opaque
//-----------------------------------------------------------------------
// #OPTIX_D
void traceAlbedo(vec2 adjustedPixelPos)
{
  const vec2 pixelCenter = adjustedPixelPos + vec2(0.5f, 0.5f);
  const vec2 inUV        = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
  const vec2 d           = inUV * 2.0 - 1.0;

  mat4 viewInv, projInv;
  // Calculate the distance from the center of the view


  // If left vire and the pixel is outside the inner circle
  if (isLeftView && dist > radius)
  {
    // If pixel is outside the middle zone(circular pattern)
    if (!skippingArea) 
    {
      viewInv = inverse(frameInfo[0].view2);
      projInv = inverse(frameInfo[0].proj2);
    }
    else { // If the pixel is an area around the middle zone (circular pattern)
      if(intertwine){      
        viewInv = inverse(frameInfo[0].view2);
        projInv = inverse(frameInfo[0].proj2);
      }
      else{
        viewInv = inverse(frameInfo[0].view);
        projInv = inverse(frameInfo[0].proj);
      }
    }
  }
  else if (!isLeftView) // If right view, draw right view
  {
    viewInv = inverse(frameInfo[0].view2);
    projInv = inverse(frameInfo[0].proj2);
  }
  else // If left view and pixel is inside the circular pattern, draw left view
  {
    viewInv = inverse(frameInfo[0].view);
    projInv = inverse(frameInfo[0].proj);
  }

  vec4 origin    = viewInv * vec4(0.0, 0.0, 0.0, 1.0);
  vec4 target    = projInv * vec4(d.x, d.y, 0.01, 1.0);
  vec4 direction = viewInv * vec4(normalize(target.xyz), 0.0);
  const uint  rayFlags  = gl_RayFlagsOpaqueEXT;
  const float tMin      = 0.001;
  const float tMax      = INFINITE;

  payloadGbuf.packAlbedo = 0;
  payloadGbuf.packNormal = 0;

  traceRayEXT(topLevelAS,     // acceleration structure
              rayFlags,       // rayFlags
              0xFF,           // cullMask
              1,              // sbtRecordOffset --- Using the Gbuffer.rchit
              0,              // sbtRecordStride
              1,              // missIndex --- Using the Gbuffer.rmiss
              origin.xyz,     // ray origin
              tMin,           // ray min range
              direction.xyz,  // ray direction
              tMax,           // ray max range
              1               // payload --- Using the GbufferPayload
  );

  gUnpackedAlbedo = unpackUnorm4x8(payloadGbuf.packAlbedo);
  gUnpackedNormal = decompress_unit_vec(payloadGbuf.packNormal);
}


void main()
{
  
  isLeftView = gl_LaunchIDEXT.x < (gl_LaunchSizeEXT.x / 2);   // Retrieve the view index
  float borderThickness = 200.0;


  /*
    Agora preciso comecar a trabalhar com os passes e ver como pegar os dados do primeiro pass
    e passar para o segundo pass
  */
  // Paint left half green in first pass, right half red in second pass
  // if(pc.passId == 0 && isLeftView)
  // {
  //   imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(0, 1, 0, 1)); // Green
  //   return;
  // }
  // else if(pc.passId == 1 && !isLeftView)
  // {
  //   imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(1, 0, 0, 1)); // Red
  //   return;
  // }


  // Adjust the pixel position for left and right views
  vec2 adjustedPixelPos = vec2(gl_LaunchIDEXT.xy);
  if (isLeftView)
  {
    adjustedPixelPos.x *= 2.0; // Scale pixel position for left view
  }
  else
  {
    adjustedPixelPos.x = (adjustedPixelPos.x - (gl_LaunchSizeEXT.x / 2)) * 2.0; // Scale and shift pixel position for right view
  }
  
  // Initialize the random number
  uint seed = xxhash32(uvec3(adjustedPixelPos, pc.frame));
  // Sampling n times the pixel
  vec3 contribAccum = vec3(0.0, 0.0, 0.0);

  /*
    Circular edge border and skip rules

    Distances from center is calculated for both views
    center: center of the whole screen
    radius: % of the smallest screen dimension
    borderThickness: thickness of the border
    dist: Po
  */
  if (isLeftView){
    vec2 center = vec2(gl_LaunchSizeEXT.x / 2.0, gl_LaunchSizeEXT.y / 2.0);
    dist = length(adjustedPixelPos.xy - center);
    radius = min(gl_LaunchSizeEXT.x/2.0, gl_LaunchSizeEXT.y) * 0.3;// Radius for the circular pattern

    // radius = 100.0;

    // skip half of the pixels outside the circular pattern
    // if (dist > radius + borderThickness && 
    //   ((gl_LaunchIDEXT.x%2 == 0 && gl_LaunchIDEXT.y%2 == 1)) || 
    //   ((gl_LaunchIDEXT.x%2 == 1 && gl_LaunchIDEXT.y%2 == 0))) 
    // {
    //   return; 
    // }


    if (dist < radius + borderThickness && dist > radius) 
    {
      skippingArea = true;
    }

    if (skippingArea) 
    {
      // float probabilityFactor = 1.0 - (dist - (radius - borderThickness)) / (2.0 * borderThickness);
    float probabilityFactor = (((radius+borderThickness)-dist) / borderThickness);
      if (rand(seed) > 0.5)
      {  // Skip 10% of the pixels in the border zone
        skipPixel = true;
        return;
      }
      else if (skippingArea && rand(seed) > probabilityFactor) 
      { // In the zone, Draw center region in more, and increases outer region as it goes further
        intertwine = true;
      }
      else
      { // Draw what it is supposed to
        skipPixel = false;
        intertwine = false;
      }
    }
  }
    

  for(uint s = 0; s < pc.maxSamples; s++)
  {
    contribAccum += samplePixel(seed, adjustedPixelPos);
  }
  contribAccum /= pc.maxSamples;

  // Saving result
  if(pc.frame == 0)
  {  // First frame, replace the value in the buffer
    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(contribAccum, 1.f));

    // #OPTIX_D
    // G-Buffers
    traceAlbedo(adjustedPixelPos);
    imageStore(gAlbedo, ivec2(gl_LaunchIDEXT.xy), gUnpackedAlbedo);
    gUnpackedNormal = (gUnpackedNormal * vec3(0.5)) + vec3(0.5);  // converting to [0..1]
    imageStore(gNormal, ivec2(gl_LaunchIDEXT.xy), vec4(gUnpackedNormal, 1));
  }
  else
  {  // Do accumulation over time
    float a         = 1.0f / float(pc.frame + 1);
    vec3  old_color = imageLoad(image, ivec2(gl_LaunchIDEXT.xy)).xyz;
    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(mix(old_color, contribAccum, a), 1.f));
  }
}
